
---
- name: Ensure basic packages present
  package:
    name:
      - git
      - curl
      - wget
      - unzip
      - python3
      - python3-pip
    state: present

- name: Set timezone
  command: timedatectl set-timezone {{ timezone }}
  when: ansible_system == "Linux"
