version: '3'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - "3000:3000"

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"

  jenkins-exporter:
    image: quay.io/prometheuscommunity/jenkins-exporter
    ports:
      - "9118:9118"

  kube-state-metrics:
    image: quay.io/coreos/kube-state-metrics
    ports:
      - "8080:8080"
