
---
- name: Deploy sample app to app nodes
  hosts: apps
  become: true
  tasks:
    - name: Ensure docker is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Run sample nginx container
      community.docker.docker_container:
        name: demo-nginx
        image: nginx:stable
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "8081:80"
