global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node'
    static_configs:
      - targets: ['192.168.1.10:9100','192.168.1.11:9100','192.168.1.12:9100','192.168.1.13:9100']
  - job_name: 'jenkins'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.1.11:8080']
